### ISSUE TITLE
undefined references for several functions

### ISSUE THREAD

**Issue by TaurVil** [udo-stenzel/network-aware-bwa#1]
Hello, I ran into some problems with undefined references when trying to compile this program. I repaired them in a haphazard manner locally by removing a couple of the "inline" annotations, but wanted to let you know and hopefully make sure I wasn't breaking anything!

bwtaln.o: In function `bwt_cal_width':
/usr/Programs/bwa_bam2bam/network-aware-bwa-master/bwtaln.c:61: undefined reference to `bwt_2occ'
bwtgap.o: In function `bwt_match_gap':
/usr/Programs/bwa_bam2bam/network-aware-bwa-master/bwtgap.c:202: undefined reference to `bwt_2occ4'
bwtsw2_core.o: In function `bsw2_connectivity':
/usr/Programs/bwa_bam2bam/network-aware-bwa-master/bwtsw2_core.c:104: undefined reference to `bwtl_2occ4'
bwtsw2_core.o: In function `bsw2_core':
/usr/Programs/bwa_bam2bam/network-aware-bwa-master/bwtsw2_core.c:476: undefined reference to `bwtl_2occ4'
/usr/Programs/bwa_bam2bam/network-aware-bwa-master/bwtsw2_core.c:529: undefined reference to `bwt_2occ4'
collect2: error: ld returned 1 exit status
make: *** [bwa] Error 1

**Comment by wjv** [comment]
I'm afraid the original author of this code has left our group some time ago, and this repository is unmaintained (and kept here mainly for archival purposes). A replacement is in the works.

However, I note that the original author has continued to update his repository. Perhaps you can have a look and see if his code works for you, and also communicate directly with him there:

https://bitbucket.org/ustenzel/network-aware-bwa/
